version: '3'

services:
  rabbitmq_dev:
    restart: always
    image: rabbitmq:3.7
    environment:
      - RABBITMQ_MNESIA_BASE=/var/lib/rabbitmq/mnesia
    volumes:
      - ./data/rabbitmq_dev:/var/lib/rabbitmq/mnesia
    networks:
      - ontask_dev

  db_dev:
    restart: always
    image: mongo:4
    command: mongod --port 27018
    ports:
      - "27018:27018"
    volumes:
      - ./data/nosql:/data/db
    networks:
      - ontask_dev

  backend_dev:
    restart: always
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/backend
    depends_on:
      - db_dev
    environment:
      - LOG_STREAM=Django
    command: uwsgi --ini uwsgi.ini --lazy-apps
    networks:
      - ontask_dev

  celery_dev:
    restart: always
    build: ./backend
    volumes:
      - ./backend:/backend
    depends_on:
      - rabbitmq_dev
      - backend_dev
    environment:
      - LOG_STREAM=Celery
    command: celery worker -A ontask --loglevel=INFO
    networks:
      - ontask_dev

  celery_beat_dev:
    restart: always
    build: ./backend
    depends_on:
      - celery_dev
    environment:
      - LOG_STREAM=CeleryBeat
    command: celery -A ontask beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    networks:
      - ontask_dev

networks:
    ontask_dev:
        driver: bridge