version: '3'

services:
  rabbitmq:
    restart: always
    image: rabbitmq:3.7
    environment:
      - RABBITMQ_MNESIA_BASE=/data/rabbitmq
    volumes: 
      - ./data/rabbitmq:/data/rabbitmq

  sql:
    restart: always
    image: postgres:10.5
    environment:
      - POSTGRES_DB=ontask
      - POSTGRES_USER=ontask
      - POSTGRES_PASSWORD=ontask
      - PGDATA=/data/db
    volumes:
      - ./data/sql:/data/db

  nosql:
    restart: always
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - ./data/nosql:/data/db

  backend:
    restart: always
    build: ./backend
    volumes:
      - ./backend:/backend
    environment:
      - ONTASK_DEVELOPMENT=true
    depends_on:
      - sql
      - nosql
    command: uwsgi --ini uwsgi.dev.ini --lazy-apps

  nginx:
    image: nginx:alpine
    volumes:
      - ./dev/nginx.conf:/etc/nginx/nginx.conf
      - ./dev/localhost.crt:/localhost.crt
      - ./dev/localhost.key:/localhost.key
    depends_on:
      - backend
    ports:
      - "8000:443"
    
  celery:
    restart: always
    build: ./backend
    environment:
      - ONTASK_DEVELOPMENT=true
    depends_on:
      - rabbitmq
      - backend
    command: celery worker -A ontask --loglevel=INFO

  celery_beat:
    restart: always
    build: ./backend
    environment:
      - ONTASK_DEVELOPMENT=true
    depends_on:
      - celery
    command: celery -A ontask beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler

  frontend:
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      - HTTPS=true
    depends_on:
      - backend
    command: npm start
