version: '3'

services:
  rabbitmq:
    restart: always
    image: rabbitmq:3.7
    environment:
      - RABBITMQ_MNESIA_BASE=/var/lib/rabbitmq/mnesia
    volumes: 
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia

  sql:
    restart: always
    image: postgres:10.5
    environment:
      - POSTGRES_DB=ontask
      - POSTGRES_USER=ontask
      - POSTGRES_PASSWORD=ontask
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./data/sql:/var/lib/postgresql/data

  nosql:
    restart: always
    image: mongo:4
    volumes:
      - ./data/nosql:/data/db

  backend:
    restart: always 
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - sql
      - nosql
    command: uwsgi --ini uwsgi.ini --lazy-apps

  celery:
    restart: always
    build: ./backend
    volumes:
      - ./backend:/backend
    depends_on:
      - rabbitmq
      - backend
    command: celery worker -A ontask --loglevel=INFO

  celery_beat:
    restart: always
    build: ./backend
    depends_on:
      - celery
    command: celery -A ontask beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
