version: '3'

services:
  rabbitmq:
    restart: always
    image: rabbitmq:3.7
    environment:
      - RABBITMQ_MNESIA_BASE=/var/lib/rabbitmq/mnesia
    volumes: 
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia

  db:
    restart: always
    image: mongo:4
    volumes:
      - ./data/nosql:/data/db

  backend:
    restart: always 
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    environment:
      - LOG_STREAM=Django
    command: uwsgi --ini uwsgi.ini --lazy-apps

  celery:
    restart: always
    build: ./backend
    volumes:
      - ./backend:/backend
    depends_on:
      - rabbitmq
      - backend
    environment:
      - LOG_STREAM=Celery
    command: celery worker -A ontask --loglevel=INFO

  celery_beat:
    restart: always
    build: ./backend
    depends_on:
      - celery
    environment:
      - LOG_STREAM=CeleryBeat
    command: celery -A ontask beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler

  flower:
    image: mher/flower
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "5555:5555"
    env_file:
      - flower.env
    depends_on:
      - celery_beat
    command: celery flower -A ontask --address=0.0.0.0 --port=5555
